export const dbCategories = [
  {
    name: "To Dad",
  },
  { name: "To Mom" },
  { name: "Committee" },
  { name: "Fruits & Vegetables" },
  { name: "To Wife" },
  { name: "Mom Doctor Fee" },
  { name: "Mom Medicines" },
  { name: "Dad Doctor Fee" },
  { name: "Dad Medicines" },
  { name: "Self Doctor Fee" },
  { name: "Self Medicines" },
  { name: "Eating Out -  Delivery" },
  { name: "Eating Out - DineIn" },
  { name: "Eating Out - Family" },
  { name: "Car Fuel - City" },
  { name: "Car Maintenance - City" },
  { name: "Car Fuel - Cultus" },
  { name: "Car Maintenance - Cultus" },
  { name: "Bike Fuel" },
  { name: "Bike Maintenance" },
  { name: "Hair / Beard Cut & Salon" },
  { name: "Mobile Recharge - Self" },
  { name: "Mobile Recharge - Others" },
  { name: "Electronics / Gadgets Purchase - Self" },
  { name: "Electronics / Gadgets Purchase - Others" },
  { name: "Meat / Mince" },
  { name: "Shopping - Wife" },
  { name: "Shopping - Mom" },
  { name: "Shopping - Dad" },
  { name: "Shopping - Others" },
];
